# Generated by Django 3.2.3 on 2021-07-14 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryPages', '0003_auto_20210714_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('Fiction', 'Science Fiction'), ('Sceince', 'Fiction'), ('Drama', 'Drama'), ('Crime', 'Crime')], max_length=50),
        ),
    ]
