# Generated by Django 3.2.5 on 2021-07-15 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import libraryPages.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryPages', '0006_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowed',
            name='DateReturn',
            field=models.DateField(default=libraryPages.models.afterWeek),
        ),
        migrations.AddField(
            model_name='borrowed',
            name='bookId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='libraryPages.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowed',
            name='userEmail',
            field=models.ForeignKey(default='nader@gg.com', on_delete=django.db.models.deletion.CASCADE, serialize=False, to='libraryPages.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowed',
            name='Date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='borrowed',
            unique_together={('bookId', 'userEmail')},
        ),
        migrations.RemoveField(
            model_name='borrowed',
            name='id',
        ),
    ]
